---
title: "Presentation"
date: "11/19/2021"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: solarized-light
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#866fa3",
  secondary_color = "#F1DE67",
  inverse_header_color = "#464a53",
  black_color = "#464a53",
  header_font_google = google_font("Atkinson Hyperlegible"),
  text_font_google   = google_font("Atkinson Hyperlegible", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  title_slide_background_color = "#FFFFFF",
  title_slide_background_size = "contain",
  base_font_size = "24px",
  extra_css = list(
    "h1" = list("margin-block-start" = "0.4rem", 
                "margin-block-end" = "0.4rem"),
    "h2" = list("margin-block-start" = "0.4rem", 
                "margin-block-end" = "0.4rem"),
    "h3" = list("margin-block-start" = "0.4rem", 
                "margin-block-end" = "0.4rem"),
    ".small" = list("font-size" = "90%"),
    ".midi" = list("font-size" = "150%"),
    ".large" = list("font-size" = "200%"),
    ".xlarge" = list("font-size" = "600%"),
    ".hand" = list("font-family" = "'Gochi Hand', cursive",
                   "font-size" = "125%"),
    ".task" = list("padding-right"    = "10px",
                   "padding-left"     = "10px",
                   "padding-top"      = "3px",
                   "padding-bottom"   = "3px",
                   "margin-bottom"    = "6px",
                   "margin-top"       = "6px",
                   "border-left"      = "solid 5px #F1DE67",
                   "background-color" = "#F1DE6750")
  )
)

```


```{r include = F}
source("licorice.R")
```


## Introduction

### Instrutor



### Teaching assistants



---

## Timetable


  


---
